entrypoints:
  web:
    address: ":80"
    # redirect: "websecure"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"


api:
  insecure: true
  dashboard: true
  debug: true

log:
  level: DEBUG

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: scope-net
    exposedByDefault: false

  file:
    filename: /etc/traefik/file-provider.yml
    watch: true


